# Generated by Django 2.2.4 on 2019-08-29 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_v360_update_credential_injector_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='is_containerized',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='instancegroup',
            name='credential',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancegroups', to='main.Credential'),
        ),
        migrations.AddField(
            model_name='instancegroup',
            name='pod_spec_override',
            field=models.TextField(blank=True, default=''),
        ),
    ]
